services:
  # app:
  #   build: ./
  #   command: ./go_todo_app
  #   ports:
  #     - 8000:8000
  #   depends_on:
  #     db:
  #       condition: service_healthy

  db:
    image: postgres:16.4
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 5s
      timeout: 3s
      retries: 3


volumes:
  pgdata:
  redis-data:
